import assert from 'node:assert/strict';
import { test } from 'node:test';
import { ApiClient, ApiError } from '../src/services/api/client.ts';
import { HuntRewardsApi, RewardOptionsApi, rewardSaveError, type RewardOptions } from '../src/services/api/rewards.ts';
import type { SessionStore, SessionTokens } from '../src/services/api/session.ts';

class Session implements SessionStore {
  getAccessToken(){return 'token'} getRefreshToken(){return null}
  saveSession(_tokens:SessionTokens){} clearSession(){}
}
function json(body:unknown,status=200){return new Response(status===204?null:JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})}
function mock(responses:Response[]){const calls:Array<{url:string;init?:RequestInit}>=[];const fetcher:typeof fetch=async(url,init)=>{calls.push({url:String(url),init});const response=responses.shift();assert.ok(response);return response};return {api:new ApiClient('https://api.test',new Session(),fetcher),calls}}
const details={provider:'tedix_inventory' as const,kind:'virtual' as const,category:'profile_badge' as const,name:null,description:null,quantity:2};
const leaderboard={id:'r1',huntId:'hunt/1',place:1,...details};
const special={id:'s1',huntId:'hunt/1',definitionKey:'precision',...details};

test('reward metadata uses authenticated backend labels, keys, and all eight definitions',async()=>{const options:RewardOptions={providers:[{key:'organizer',label:'Organizer'},{key:'tedix_inventory',label:'Tedix inventory'}],kinds:[{key:'physical',label:'Physical'},{key:'virtual',label:'Virtual'}],virtualCategories:[{key:'profile_badge',label:'Backend badge label'}],specialAwardDefinitions:Array.from({length:8},(_,i)=>({key:`award-${i}`,scope:i<4?'team':'personal',name:`Award ${i}`,rule:'Rule',description:'Description',eligibility:'Eligibility'}))};const {api,calls}=mock([json(options)]);assert.deepEqual(await new RewardOptionsApi(api).getOptions(),options);assert.equal(calls[0].url,'https://api.test/api/reward-options');assert.equal(new Headers(calls[0].init?.headers).get('authorization'),'Bearer token');assert.equal(options.specialAwardDefinitions.length,8);assert.equal(options.virtualCategories[0].label,'Backend badge label')})

test('empty and persisted Hunt reward lists map without frontend substitutions',async()=>{const {api,calls}=mock([json({leaderboard:[],specialAwards:[]}),json({leaderboard:[leaderboard],specialAwards:[special]})]);const rewards=new HuntRewardsApi(api);assert.deepEqual(await rewards.list('hunt/1'),{leaderboard:[],specialAwards:[]});assert.deepEqual(await rewards.list('hunt/1'),{leaderboard:[leaderboard],specialAwards:[special]});assert.equal(calls[0].url,'https://api.test/api/hunts/hunt%2F1/rewards')})

test('leaderboard CRUD sends numeric place and canonical keys and uses returned records',async()=>{const updated={...leaderboard,place:2,provider:'organizer' as const,kind:'physical' as const,category:null,name:'Medal',description:null,quantity:4};const {api,calls}=mock([json(leaderboard,201),json(updated),json(undefined,204)]);const rewards=new HuntRewardsApi(api);const created=await rewards.createLeaderboard('h',{place:1,...details});assert.deepEqual(created,leaderboard);assert.deepEqual(JSON.parse(String(calls[0].init?.body)),{place:1,...details});assert.equal(typeof JSON.parse(String(calls[0].init?.body)).place,'number');assert.deepEqual(await rewards.updateLeaderboard('h','r/1',{place:2,provider:'organizer',kind:'physical',category:null,name:'Medal',description:null,quantity:4}),updated);await rewards.deleteLeaderboard('h','r/1');assert.equal(calls[2].url,'https://api.test/api/hunts/h/rewards/leaderboard/r%2F1');assert.equal(calls[2].init?.method,'DELETE')})

test('special CRUD persists definitionKey but never definition metadata',async()=>{const input={definitionKey:'precision',...details};const {api,calls}=mock([json(special,201),json(special),json(undefined,204)]);const rewards=new HuntRewardsApi(api);await rewards.createSpecial('h',input);const payload=JSON.parse(String(calls[0].init?.body));assert.equal(payload.definitionKey,'precision');assert.equal('rule' in payload,false);assert.equal('eligibility' in payload,false);assert.equal('definitionName' in payload,false);await rewards.updateSpecial('h','s1',input);await rewards.deleteSpecial('h','s1');assert.equal(calls[1].init?.method,'PATCH');assert.equal(calls[2].url,'https://api.test/api/hunts/h/rewards/special/s1')})

test('reward errors are safe and status/code-specific',()=>{assert.equal(rewardSaveError(new ApiError('raw',400,'bad_request')),'Check the reward details and try again.');assert.equal(rewardSaveError(new ApiError('raw',403,'http')),"You don't have permission to change rewards for this Hunt.");assert.equal(rewardSaveError(new ApiError('raw',404,'http')),'This reward could not be found.');assert.equal(rewardSaveError(new ApiError('raw',409,'conflict',{error:'reward_conflict'})),'That reward allocation is already configured.');assert.equal(rewardSaveError(new ApiError('raw',409,'conflict',{error:'invalid_hunt_state'})),'Rewards are locked because this Hunt is no longer a draft.');assert.equal(rewardSaveError(new Error('database detail')),"We couldn't save this reward. Please try again.")})
