import { FormEvent, ReactNode, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../app/providers/AuthProvider'
import { authErrorMessage } from '../features/auth/errors'

function AccessShell({ children }: { children: ReactNode }) {
  return <main className="min-h-dvh bg-slate-950 px-5 py-10 text-white"><div className="mx-auto flex min-h-[calc(100dvh-5rem)] w-full max-w-md flex-col justify-center"><Link className="mb-8 text-sm font-black uppercase tracking-[0.2em]" to="/">TedixHunt</Link>{children}</div></main>
}

export function ProfessionalSignInPage({ type }: { type: 'creator' | 'admin' }) {
  const navigate=useNavigate()
  const { loginCreator, registerCreator } = useAuth()
  const [email,setEmail]=useState('')
  const [password,setPassword]=useState('')
  const [name,setName]=useState('')
  const [registering,setRegistering]=useState(false)
  const [error,setError]=useState('')
  const [isSubmitting,setIsSubmitting]=useState(false)
  const submitting=useRef(false)
  const creator=type==='creator'
  async function submit(event:FormEvent){event.preventDefault();if(submitting.current)return;if(!email.includes('@')||password.length<6){setError('Enter a valid email and password.');return}if(creator&&registering&&!name.trim()){setError('Enter your name.');return}if(!creator){navigate('/admin/verify');return}submitting.current=true;setIsSubmitting(true);setError('');try{if(registering)await registerCreator({email:email.trim(),password,name:name.trim()});else await loginCreator({email:email.trim(),password});navigate('/creator',{replace:true})}catch(caught){setError(authErrorMessage(caught,registering?'register':'login'))}finally{submitting.current=false;setIsSubmitting(false)}}
  return <AccessShell><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">{creator?'Creator Studio':'Platform Administration'}</p><h1 className="mt-3 text-4xl font-black tracking-tight">{creator?(registering?'Create a Creator account':'Sign in to create templates'):'Admin sign in'}</h1><p className="mt-4 leading-7 text-slate-300">{creator?'Create, test and submit Competition Templates.':'Review templates, safety alerts and platform settings.'}</p><form className="mt-7 rounded-2xl border border-white/10 bg-white/[0.05] p-5" onSubmit={submit}>{creator&&registering&&<><label className="text-sm font-bold" htmlFor="creator-name">Name</label><input autoComplete="name" className="mt-2 min-h-14 w-full rounded-xl border border-white/15 bg-white/[0.06] px-4" id="creator-name" onChange={event=>setName(event.target.value)} value={name}/></>}<label className={`${creator&&registering?'mt-5 block':''} text-sm font-bold`} htmlFor={`${type}-email`}>Email address</label><input autoComplete="email" className="mt-2 min-h-14 w-full rounded-xl border border-white/15 bg-white/[0.06] px-4 outline-none focus:border-emerald-300" id={`${type}-email`} onChange={event=>{setEmail(event.target.value);setError('')}} type="email" value={email}/><label className="mt-5 block text-sm font-bold" htmlFor={`${type}-password`}>Password</label><input autoComplete={registering?'new-password':'current-password'} className="mt-2 min-h-14 w-full rounded-xl border border-white/15 bg-white/[0.06] px-4 outline-none focus:border-emerald-300" id={`${type}-password`} onChange={event=>{setPassword(event.target.value);setError('')}} type="password" value={password}/>{error&&<p className="mt-4 rounded-lg bg-amber-300/10 px-3 py-2 text-sm font-bold text-amber-200" role="alert">{error}</p>}<button className="mt-5 min-h-14 w-full rounded-xl bg-emerald-400 px-5 font-black text-slate-950 disabled:opacity-60" disabled={isSubmitting} type="submit">{isSubmitting?'Please wait…':creator?(registering?'Create account':'Open Creator Studio'):'Continue to 2FA'}</button>{creator&&<button className="mt-2 min-h-11 w-full text-sm font-bold text-emerald-300" onClick={()=>{setRegistering(!registering);setError('')}} type="button">{registering?'Already have an account? Sign in':'New Creator? Create an account'}</button>}</form></AccessShell>
}

export function AdminVerificationPage(){const navigate=useNavigate();const [code,setCode]=useState('246810');const [error,setError]=useState('');function verify(event:FormEvent){event.preventDefault();if(!/^\d{6}$/.test(code)){setError('Enter the six-digit verification code.');return}navigate('/admin')}return <AccessShell><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">Security check</p><h1 className="mt-3 text-4xl font-black tracking-tight">Two-factor verification</h1><p className="mt-4 leading-7 text-slate-300">Confirm the verification code to open the Admin Console.</p><form className="mt-7 rounded-2xl border border-white/10 bg-white/[0.05] p-5" onSubmit={verify}><label className="text-sm font-bold" htmlFor="admin-code">Verification code</label><input autoComplete="one-time-code" className="mt-2 min-h-16 w-full rounded-xl border border-white/15 bg-white/[0.06] px-4 text-center text-2xl font-black tracking-[0.3em] outline-none focus:border-emerald-300" id="admin-code" inputMode="numeric" maxLength={6} onChange={event=>{setCode(event.target.value.replace(/\D/g,''));setError('')}} value={code}/>{error&&<p className="mt-4 text-sm font-bold text-amber-200" role="alert">{error}</p>}<button className="mt-5 min-h-14 w-full rounded-xl bg-emerald-400 px-5 font-black text-slate-950" type="submit">Open Admin Console</button></form></AccessShell>}
